name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-python:
    name: Backend (pytest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r backend/requirements.txt
      - name: Run pytest
        run: python -m pytest backend/tests

  backend-node:
    name: Worker (Node tests)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      - name: Install dependencies
        working-directory: backend
        run: npm ci
      - name: Run worker tests
        working-directory: backend
        run: npm test

  frontend:
    name: Web (Vitest & build)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      - name: Install dependencies
        working-directory: web
        run: npm ci
      - name: Run Vitest suite
        working-directory: web
        run: npm test -- --run
      - name: Build app
        working-directory: web
        run: npm run build

  docker-build:
    name: Docker build check
    runs-on: ubuntu-latest
    needs: [backend-python, backend-node, frontend]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build backend images
        run: |
          docker build --target api -f backend/Dockerfile .
          docker build --target worker -f backend/Dockerfile .
      - name: Build AI core image
        run: docker build -f ai_core/Dockerfile ai_core
      - name: Build web image
        run: docker build -f web/Dockerfile web
